name = "modpackkkkkk"
author = "undefined"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0714bac442b2735901c0c00e68f13d3ca8246996ae53fa5807b9707482c78eb6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
