name = "modpackkkkkk"
author = "undefined"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9dda1737e29df2a78f273d328bf6be32ca4d19a96b0b2184c69b5bdb7a26370"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
