#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jun 03 07:07:59 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=Spooklementary_v2.0.4.zip
