#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 14 07:43:53 GMT-03:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=8
shaderPack=ComplementaryUnbound_r5.8.1.zip
