name = "modpackkkkkk"
author = "undefined"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40ed07a446d17d3e9b911ceb7860e62b2a806d1831002cfb8f7afe6e6443466e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
