name = "modpackkkkkk"
author = "undefined"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75d534b4c3bf3d907b27b586cdaf58da6da95048c97f0d71fe5a095abf162e39"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
